### PR TITLE
Add margin to header section

### PR DESCRIPTION
**Pull request by maissen**

### CODE REVIEW

**Review by maiss-japan — APPROVED** [review]
that sounds great, well done Maissen

**Review by Anatoly-jpn — CHANGES_REQUESTED** [review]
but there's a lot of missing things to add to the header section !

**Comment by maiss-japan** [comment]
> 

list then the missing things !

**Comment by maissen** [comment]
The majority of our front end members accepted to add the new modifications !

**Review by maiss-japan — APPROVED** [review]

**Review by Anatoly-jpn — APPROVED** [review]

**Pull request merged**
